export const DataTvShow = {
  page: 1,
  results: [
    {
      adult: false,
      backdrop_path: "/iEg2LHsFV3vC6LywkBAL3c1n9PP.jpg",
      genre_ids: [10767, 35],
      id: 61818,
      origin_country: ["US"],
      original_language: "en",
      original_name: "Late Night with Seth Meyers",
      overview:
        'Seth Meyers, who is "Saturday Night Live’s" longest serving anchor on the show’s wildly popular "Weekend Update," takes over as host of NBC’s "Late Night" — home to A-list celebrity guests, memorable comedy and the best in musical talent. As the Emmy Award-winning head writer for "SNL," Meyers has established a reputation for sharp wit and perfectly timed comedy, and has gained fame for his spot-on jokes and satire. Meyers takes his departure from "SNL" to his new post at "Late Night," as Jimmy Fallon moves to "The Tonight Show".',
      popularity: 653.389,
      poster_path: "/rw0QaegwgKbRoB2CZe2lfewltT9.jpg",
      first_air_date: "2014-02-25",
      name: "Late Night with Seth Meyers",
      vote_average: 5.3,
      vote_count: 107,
    },
    {
      adult: false,
      backdrop_path: "/hHMWfDlqKisD5zVcZfz3KEw5U3v.jpg",
      genre_ids: [18, 10751],
      id: 50821,
      origin_country: ["HU"],
      original_language: "hu",
      original_name: "Barátok közt",
      overview: "Miklós introduces viewers into the world of Money and Charm.",
      popularity: 586.8624,
      poster_path: "/kBBbSgNchtMvsgD6z1oI1RRluHP.jpg",
      first_air_date: "1998-10-26",
      name: "Among Friends",
      vote_average: 3.2,
      vote_count: 14,
    },
    {
      adult: false,
      backdrop_path: "/qLMfcvdCcCGD2BNLH8b6ZCBuO7D.jpg",
      genre_ids: [10763, 35],
      id: 2224,
      origin_country: ["US"],
      original_language: "en",
      original_name: "The Daily Show",
      overview:
        "The World's Fakest News Team tackle the biggest stories in news, politics and pop culture.",
      popularity: 674.795,
      poster_path: "/ixcfyK7it6FjRM36Te4OdblAq4X.jpg",
      first_air_date: "1996-07-22",
      name: "The Daily Show",
      vote_average: 6.354,
      vote_count: 576,
    },
    {
      adult: false,
      backdrop_path: "/gMMnf8VRg3Z98WaFmOLr9Jk8pIs.jpg",
      genre_ids: [35, 10767],
      id: 63770,
      origin_country: ["US"],
      original_language: "en",
      original_name: "The Late Show with Stephen Colbert",
      overview:
        "Stephen Colbert brings his signature satire and comedy to The Late Show with Stephen Colbert, the #1 show in late night, where he talks with an eclectic mix of guests about what is new and relevant in the worlds of politics, entertainment, business, music, technology, and more. Featuring bandleader Jon Batiste with his band Stay Human, the Emmy Award-nominated show is broadcast from the historic Ed Sullivan Theater. Stephen Colbert, Chris Licht, Tom Purcell, and Jon Stewart are executive producers. Barry Julien and Denise Rehrig serve as co-executive producers.must watch",
      popularity: 794.677,
      poster_path: "/9jkThAGYj2yp8jsS6Nriy5mzKFT.jpg",
      first_air_date: "2015-09-08",
      name: "The Late Show with Stephen Colbert",
      vote_average: 6.343,
      vote_count: 309,
    },
    {
      adult: false,
      backdrop_path: "/amtOltTVcK9vQtL1iQS6p3LBi05.jpg",
      genre_ids: [10767],
      id: 62223,
      origin_country: ["US"],
      original_language: "en",
      original_name: "The Late Late Show with James Corden",
      overview:
        "Once Craig Ferguson retires, James Corden will be taking over The Late Late Show. The show is a late night talk show that interviews celebrities and has its own bits. And of course, it's all hosted by James Corden.",
      popularity: 363.4867,
      poster_path: "/qPmVoG8G9tc1nN8ZwGV2zYcknit.jpg",
      first_air_date: "2015-03-23",
      name: "The Late Late Show with James Corden",
      vote_average: 5.312,
      vote_count: 138,
    },
    {
      adult: false,
      backdrop_path: "/7jEnft2CLNbILWAiBRIBrXNN7Qh.jpg",
      genre_ids: [10767, 35],
      id: 498,
      origin_country: ["US"],
      original_language: "en",
      original_name: "Late Show with David Letterman",
      overview:
        "Late Show with David Letterman is an American late-night talk show hosted by David Letterman on CBS. The show debuted on August 30, 1993, and is produced by Letterman's production company, Worldwide Pants Incorporated and CBS Television Studios. The show's music director and band-leader of the house band, the CBS Orchestra, is Paul Shaffer. The head writer is Matt Roberts and the announcer is Alan Kalter. Of the major U.S. late-night programs, Late Show ranks second in cumulative average viewers over time and third in number of episodes over time. The show leads other late night shows in ad revenue with $271 million in 2009.\n\nIn most U.S. markets the show airs at 11:35 p.m. Eastern/Pacific time, but is recorded Monday through Wednesday at 4:30 p.m., and Thursdays at 3:30 p.m and 6:00 p.m. The second Thursday episode usually airs on Friday of that week.\n\nIn 2002, Late Show with David Letterman was ranked No. 7 on TV Guide's 50 Greatest TV Shows of All Time. CBS has a contract with Worldwide Pants to continue the show through 2014; by then, Letterman will surpass Johnny Carson as the longest tenured late-night talk show host.",
      popularity: 843.036,
      poster_path: "/fTBC5EpsgKmli9VQcJMtqQ08Qj4.jpg",
      first_air_date: "1993-08-30",
      name: "Late Show with David Letterman",
      vote_average: 6.325,
      vote_count: 154,
    },
    {
      adult: false,
      backdrop_path: "/m0bV3qBiJBBlpFaaKjwHo13MVjm.jpg",
      genre_ids: [35, 10767],
      id: 14981,
      origin_country: ["US"],
      original_language: "en",
      original_name: "The Late Late Show with Craig Ferguson",
      overview:
        "The Late Late Show with Craig Ferguson is an American late-night talk show hosted by Scottish American comedian Craig Ferguson, who is the third regular host of the Late Late Show franchise. It follows Late Show with David Letterman in the CBS late-night lineup, airing weekdays in the US at 12:37 a.m. It is taped in front of a live studio audience from Monday to Friday at CBS Television City in Los Angeles, California, directly above the Bob Barker Studio. It is produced by David Letterman's production company Worldwide Pants Incorporated and CBS Television Studios.\n\nSince becoming host on January 3, 2005, after Craig Kilborn and Tom Snyder, Ferguson has achieved the highest ratings since the show's inception in 1995. While the majority of the episodes focus on comedy, Ferguson has also addressed difficult subject matter, such as the deaths of his parents, and undertaken serious interviews, such as one with Desmond Tutu, which earned the show a 2009 Peabody Award.",
      popularity: 387.2888,
      poster_path: "/gGC7zSDgG0FY0MbM1pjfhTCWQBI.jpg",
      first_air_date: "2005-01-03",
      name: "The Late Late Show with Craig Ferguson",
      vote_average: 6.792,
      vote_count: 106,
    },
    {
      adult: false,
      backdrop_path: "/mSkisNewxu55Ivar5EubhcIuoqn.jpg",
      genre_ids: [10764],
      id: 30957,
      origin_country: ["US", "GB"],
      original_language: "en",
      original_name: "The Amazing Race",
      overview:
        "This reality competition sees teams embark on a trek around the world to amazing destinations where they must compete in a series of challenges, some mental and some physical. Only when the tasks are completed will they learn of their next location. Teams who are the farthest behind will gradually be eliminated as the contest progresses, with the first team to arrive at the final destination winning the race and the $1 million prize.",
      popularity: 606.2099,
      poster_path: "/x1jq0atcQg6UkaZpco0kFL6QHuM.jpg",
      first_air_date: "2001-09-05",
      name: "The Amazing Race",
      vote_average: 6.9,
      vote_count: 152,
    },
    {
      adult: false,
      backdrop_path: "/6jGVOu5NvnmSKh28ByWAJrTOEH2.jpg",
      genre_ids: [35, 10767],
      id: 59941,
      origin_country: ["US"],
      original_language: "en",
      original_name: "The Tonight Show Starring Jimmy Fallon",
      overview:
        "After Jay Leno's second retirement from the program, Jimmy Fallon stepped in as his permanent replacement. After 42 years in Los Angeles the program was brought back to New York.",
      popularity: 523.1162,
      poster_path: "/g4amxJvtpnY79J77xeamnAEUO8r.jpg",
      first_air_date: "2014-02-17",
      name: "The Tonight Show Starring Jimmy Fallon",
      vote_average: 5.853,
      vote_count: 340,
    },
    {
      adult: false,
      backdrop_path: "/kA50bkSC6bw5ZkutYrN9sLD9CZ9.jpg",
      genre_ids: [10767, 35],
      id: 22980,
      origin_country: ["US"],
      original_language: "en",
      original_name: "Watch What Happens Live with Andy Cohen",
      overview:
        "Bravo network executive Andy Cohen discusses pop culture topics with celebrities and reality show personalities.",
      popularity: 579.2446,
      poster_path: "/onSD9UXfJwrMXWhq7UY7hGF2S1h.jpg",
      first_air_date: "2009-07-16",
      name: "Watch What Happens Live with Andy Cohen",
      vote_average: 5.061,
      vote_count: 74,
    },
    {
      adult: false,
      backdrop_path: "/lksigd4PnpvvIY9oPHW2DEnHh5H.jpg",
      genre_ids: [],
      id: 70558,
      origin_country: ["US"],
      original_language: "en",
      original_name: "NPR Tiny Desk Concerts",
      overview:
        "Intimate musical performances, recorded live at the desk of All Songs Considered host Bob Boilen.",
      popularity: 560.791,
      poster_path: "/sJ6HdzajIVkC5G2kRROhNu8at43.jpg",
      first_air_date: "2008-04-22",
      name: "NPR Tiny Desk Concerts",
      vote_average: 7.8,
      vote_count: 8,
    },
    {
      adult: false,
      backdrop_path: "/2o0cVL6fOa06aXd5xogZhD1h4ce.jpg",
      genre_ids: [10766, 18],
      id: 14686,
      origin_country: ["DE"],
      original_language: "de",
      original_name: "Alles was zählt",
      overview:
        "Alles was zählt is a German television soap opera first broadcast on RTL on September 4, 2006. The original plot revolved around Diana Sommer's dream to become a world class ice skater. She fell in love with Julian Herzog, who signed her at the prestigious Steinkamp Sport and Wellness Center, run by the unscrupulous Steinkamp dynasty. Diana and Julian eventually became a couple, but in November 2007, Julian suffered a brain hemorrhage and died during their wedding. Diana remained in Essen until January 2009, when she left to join a skating centre in Halle. The story continues to revolve around the Steinkamp Sport and Wellness Centre and its quest to become a sporting powerhouse, as well as the lives of the characters who work at and around the Centre.",
      popularity: 506.4071,
      poster_path: "/2qup6w78HhDiSii7v8vYgfEsz6E.jpg",
      first_air_date: "2006-09-04",
      name: "Alles was zählt",
      vote_average: 5,
      vote_count: 7,
    },
    {
      adult: false,
      backdrop_path: "/3EGjqKhVHGsvNHvBIbxmqS17Aal.jpg",
      genre_ids: [10767, 10763],
      id: 224,
      origin_country: ["GB"],
      original_language: "en",
      original_name: "Matc",
    },
  ],
};
