// https://image.tmdb.org/t/p/w780/poster_path atau backdrop_path

export const DataMovie = {
  page: 1,
  results: [
    {
      backdrop_path: "/oRxHRlSetf49evkXLsqkAzofJo2.jpg",
      id: 803796,
      title: "KPop Demon Hunters",
      original_title: "KPop Demon Hunters",
      overview:
        "When K-pop superstars Rumi, Mira and Zoey aren't selling out stadiums, they're using their secret powers to protect their fans from supernatural threats.",
      poster_path: "/dt7kn47oksRCY4FLkTwVVCDq93Y.jpg",
      media_type: "movie",
      adult: false,
      original_language: "en",
      genre_ids: [16, 14, 28, 10402, 35],
      popularity: 95.2883,
      release_date: "2025-06-20",
      video: false,
      vote_average: 8.4,
      vote_count: 26,
    },
    {
      backdrop_path: "/uIpJPDNFoeX0TVml9smPrs9KUVx.jpg",
      id: 574475,
      title: "Final Destination Bloodlines",
      original_title: "Final Destination Bloodlines",
      overview:
        "Plagued by a violent recurring nightmare, college student Stefanie heads home to track down the one person who might be able to break the cycle and save her family from the grisly demise that inevitably awaits them all.",
      poster_path: "/6WxhEvFsauuACfv8HyoVX6mZKFj.jpg",
      media_type: "movie",
      adult: false,
      original_language: "en",
      genre_ids: [27, 9648],
      popularity: 1179.7021,
      release_date: "2025-05-14",
      video: false,
      vote_average: 7.213,
      vote_count: 1041,
    },
    {
      backdrop_path: "/yb1YNS9zaxbwdQBaYIfIKxWD65q.jpg",
      id: 1100988,
      title: "28 Years Later",
      original_title: "28 Years Later",
      overview:
        "Twenty-eight years since the rage virus escaped a biological weapons laboratory, now, still in a ruthlessly enforced quarantine, some have found ways to exist amidst the infected. One such group lives on a small island connected to the mainland by a single, heavily-defended causeway. When one member departs on a mission into the dark heart of the mainland, he discovers secrets, wonders, and horrors that have mutated not only the infected but other survivors as well.",
      poster_path: "/361hRZoG91Nw6qXaIKuGoogQjix.jpg",
      media_type: "movie",
      adult: false,
      original_language: "en",
      genre_ids: [27, 53, 878],
      popularity: 181.447,
      release_date: "2025-06-18",
      video: false,
      vote_average: 7.359,
      vote_count: 110,
    },
    {
      backdrop_path: "/fWOagGfFtMm70U8BtWPlVRW6efu.jpg",
      id: 259669,
      name: "Olympo",
      original_name: "Olympo",
      overview:
        "When a swimmer collapses at a high-performance sports center, Amaia investigates the extreme risks her fellow athletes are taking to feed their ambition.",
      poster_path: "/6BgcsLnjFiizUFSZchctgeZJRzY.jpg",
      media_type: "tv",
      adult: false,
      original_language: "es",
      genre_ids: [18, 9648],
      popularity: 57.8912,
      first_air_date: "2025-06-20",
      vote_average: 5.8,
      vote_count: 5,
      origin_country: ["ES"],
    },
    {
      backdrop_path: "/kootCU91JSYiQZwkJgHgyb4tz9m.jpg",
      id: 254544,
      name: "The Waterfront",
      original_name: "The Waterfront",
      overview:
        "A prominent North Carolina fishing family wades into treacherous waters to keep their crumbling business empire afloat.",
      poster_path: "/uRzJaOysinMti88BGuu8m8shVCp.jpg",
      media_type: "tv",
      adult: false,
      original_language: "en",
      genre_ids: [18, 80],
      popularity: 52.5141,
      first_air_date: "2025-06-19",
      vote_average: 8.55,
      vote_count: 10,
      origin_country: ["US"],
    },
    {
      backdrop_path: "/mMS24Uh4AsgkchTFFQaOwFnFDnO.jpg",
      id: 1061474,
      title: "Superman",
      original_title: "Superman",
      overview:
        "Superman, a journalist in Metropolis, embarks on a journey to reconcile his Kryptonian heritage with his human upbringing as Clark Kent.",
      poster_path: "/dHJCnxia2PMhirSGMTKiMslv8Yc.jpg",
      media_type: "movie",
      adult: false,
      original_language: "en",
      genre_ids: [28, 12, 878],
      popularity: 40.1156,
      release_date: "2025-07-09",
      video: false,
      vote_average: 0,
      vote_count: 0,
    },
    {
      backdrop_path: "/idUuT7vqq9GvdCZCFilEMiziyJU.jpg",
      id: 1428264,
      title: "Semi-Soeter",
      original_title: "Semi-Soeter",
      overview:
        "Power couple Jaci and JP find themselves in a bumpy predicament when a new work pitch for a baby brand forces them to play the perfect pretend parents.",
      poster_path: "/xTJXvW3u16MwMwGYnG1k2R96zYS.jpg",
      media_type: "movie",
      adult: false,
      original_language: "af",
      genre_ids: [10749, 35],
      popularity: 12.5964,
      release_date: "2025-06-19",
      video: false,
      vote_average: 4,
      vote_count: 4,
    },
    {
      backdrop_path: "/mBDoBHUZHHy9WG7dRFndjB8adhc.jpg",
      id: 1022787,
      title: "Elio",
      original_title: "Elio",
      overview:
        "Elio, a space fanatic with an active imagination, finds himself on a cosmic misadventure where he must form new bonds with eccentric alien lifeforms, navigate a crisis of intergalactic proportions and somehow discover who he is truly meant to be.",
      poster_path: "/w2ARwtc1zoh0pyfwmyhpZHwuXgK.jpg",
      media_type: "movie",
      adult: false,
      original_language: "en",
      genre_ids: [10751, 35, 12, 16, 878],
      popularity: 77.796,
      release_date: "2025-06-18",
      video: false,
      vote_average: 6.903,
      vote_count: 36,
    },
    {
      backdrop_path: "/7HqLLVjdjhXS0Qoz1SgZofhkIpE.jpg",
      id: 1087192,
      title: "How to Train Your Dragon",
      original_title: "How to Train Your Dragon",
      overview:
        "On the rugged isle of Berk, where Vikings and dragons have been bitter enemies for generations, Hiccup stands apart, defying centuries of tradition when he befriends Toothless, a feared Night Fury dragon. Their unlikely bond reveals the true nature of dragons, challenging the very foundations of Viking society.",
      poster_path: "/q5pXRYTycaeW6dEgsCrd4mYPmxM.jpg",
      media_type: "movie",
      adult: false,
      original_language: "en",
      genre_ids: [28, 10751, 14],
      popularity: 349.6505,
      release_date: "2025-06-06",
      video: false,
      vote_average: 8.036,
      vote_count: 334,
    },
    {
      backdrop_path: "/fXpsbFfQkIsj1MF3FRJh9JgO6Qq.jpg",
      id: 203367,
      name: "The Litchi Road",
      original_name: "长安的荔枝",
      overview:
        "The story follows Li Shande, a man deceived by his colleagues and demoted from his supervisory role. Now forced to become the “Lychee Envoy,” he faces a near-impossible mission to deliver fresh lychees from Lingnan to Chang’an as a birthday gift for the Noble Consort. The saying goes that lychees change color in one day, lose their fragrance in two, and their flavor in three days. With more than 5,000 li between Lingnan and Chang’an, and under tight deadlines with limited resources, how can he possibly pull it off?",
      poster_path: "/egFbeyzLU2l0quqGVaRoYRNsmET.jpg",
      media_type: "tv",
      adult: false,
      original_language: "zh",
      genre_ids: [18],
      popularity: 32.2702,
      first_air_date: "2025-06-07",
      vote_average: 8.1,
      vote_count: 9,
      origin_country: ["CN"],
    },
    {
      backdrop_path: "/3s7uwQKH0WmaeO7VCqAOK3C5gjF.jpg",
      id: 170,
      title: "28 Days Later",
      original_title: "28 Days Later",
      overview:
        "Twenty-eight days after a killer virus was accidentally unleashed from a British research facility, a small group of London survivors are caught in a desperate struggle to protect themselves from the infected. Carried by animals and humans, the virus turns those it infects into homicidal maniacs -- and it's absolutely impossible to contain.",
      poster_path: "/sQckQRt17VaWbo39GIu0TMOiszq.jpg",
      media_type: "movie",
      adult: false,
      original_language: "en",
      genre_ids: [27, 53, 878],
      popularity: 96.878,
      release_date: "2002-10-31",
      video: false,
      vote_average: 7.238,
      vote_count: 7257,
    },
    {
      backdrop_path: "/wN47m8DMp8byXfMBQl4rdfu4xvx.jpg",
      id: 1327872,
      title: "Frozen: The Hit Broadway Musical",
      original_title: "Frozen: The Hit Broadway Musical",
      overview:
        "Young princess Anna of Arendelle dreams about finding true love at her sister Elsa’s coronation. Fate takes her on a dangerous journey in an attempt to end the eternal winter that has fallen over the kingdom. She's accompanied by ice delivery man Kristoff, his reindeer Sven, and snowman Olaf. On an adventure where she will find out what friendship, courage, family, and true love really means.",
      poster_path: "/9iLk2GrFYwvt8ZmKMDmzWmGZfNZ.jpg",
      media_type: "movie",
      adult: false,
      original_language: "en",
      genre_ids: [10402, 10751, 14],
      popularity: 10.2334,
      release_date: "2025-06-20",
      video: false,
      vote_average: 7,
      vote_count: 3,
    },
    {
      backdrop_path: "/nAxGnGHOsfzufThz20zgmRwKur3.jpg",
      id: 1233413,
      title: "Sinners",
      original_title: "Sinners",
      overview:
        "Trying to leave their troubled lives behind, twin brothers return to their hometown to start again, only to discover that an even greater evil is waiting to welcome them back.",
      poster_path: "/yqsCU5XOP2mkbFamzAqbqntmfav.jpg",
      media_type: "movie",
      adult: false,
      original_language: "en",
      genre_ids: [27, 53, 14],
      popularity: 197.5341,
      release_date: "2025-04-16",
      video: false,
      vote_average: 7.549,
      vote_count: 1563,
    },
    {
      backdrop_path: "/lOje1iz4VYWELYWRkZAwI7oIJd0.jpg",
      id: 1239193,
      title: "Deep Cover",
      original_title: "Deep Cover",
      overview:
        "Kat is an improv comedy teacher beginning to question if she’s missed her shot at success. When an undercover cop offers her the role of a lifetime, she recruits two of her students to infiltrate London’s gangland by impersonating dangerous criminals.",
      poster_path: "/euM8fJvfH28xhjGy25LiygxfkWc.jpg",
      media_type: "movie",
      adult: false,
      original_language: "en",
      genre_ids: [28, 35, 80],
      popularity: 219.3617,
      release_date: "2025-06-12",
      video: false,
      vote_average: 6.74,
      vote_count: 154,
    },
    {
      backdrop_path: "/6van4BavoNXaZhCPdzLHNQ4Uc8H.jpg",
      id: 1087891,
      title: "The Amateur",
      original_title: "The Amateur",
      overview:
        "After his life is turned upside down when his wife is killed in a London terrorist attack, a brilliant but introverted CIA decoder takes matters into his own hands when his supervisors refuse to take action.",
      poster_path: "/SNEoUInCa5fAgwuEBMIMBGvkkh.jpg",
      media_type: "movie",
      adult: false,
      original_language: "en",
      genre_ids: [53, 28],
      popularity: 334.9235,
      release_date: "2025-04-09",
      video: false,
      vote_average: 6.929,
      vote_count: 560,
    },
    {
      backdrop_path: "/1Lz0CmgukN8KyzxIn8gGe4NLV3D.jpg",
      id: 911430,
      title: "F1 The Movie",
      original_title: "F1 The Movie",
      overview:
        "Racing legend Sonny Hayes is coaxed out of retirement to lead a struggling Formula 1 team—and mentor a young hotshot driver—while chasing one more chance at glory.",
      poster_path: "/9JePWGvgg1t4BOojyZEVQdOWjXO.jpg",
      media_type: "movie",
      adult: false,
      original_language: "en",
      genre_ids: [28, 18],
      popularity: 51.5554,
      release_date: "2025-06-25",
      video: false,
      vote_average: 9,
      vote_c: null,
    },
  ],
};
